// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB996lP_dTW3nfepMyLhG2RTp3e2iHauPU',
    appId: '1:184737709866:web:9bb5484e4381627186e853',
    messagingSenderId: '184737709866',
    projectId: 'music-app-f8062',
    authDomain: 'music-app-f8062.firebaseapp.com',
    storageBucket: 'music-app-f8062.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvPnAwL6NucTyPJ0EeHM6bJkmxv6EsqI',
    appId: '1:184737709866:android:bcf9fbf552017c5586e853',
    messagingSenderId: '184737709866',
    projectId: 'music-app-f8062',
    storageBucket: 'music-app-f8062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjBlE9wPcYjFF3KJHcM8o2YiuO9srhH4w',
    appId: '1:184737709866:ios:43d4ae08bfe6f56786e853',
    messagingSenderId: '184737709866',
    projectId: 'music-app-f8062',
    storageBucket: 'music-app-f8062.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjBlE9wPcYjFF3KJHcM8o2YiuO9srhH4w',
    appId: '1:184737709866:ios:43d4ae08bfe6f56786e853',
    messagingSenderId: '184737709866',
    projectId: 'music-app-f8062',
    storageBucket: 'music-app-f8062.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB996lP_dTW3nfepMyLhG2RTp3e2iHauPU',
    appId: '1:184737709866:web:917069a48d8e9eac86e853',
    messagingSenderId: '184737709866',
    projectId: 'music-app-f8062',
    authDomain: 'music-app-f8062.firebaseapp.com',
    storageBucket: 'music-app-f8062.appspot.com',
  );
}
